CREATE TABLE IF NOT EXISTS Users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Packages (
    id SERIAL PRIMARY KEY,
    location VARCHAR(255) NOT NULL,
    temperature NUMERIC(5,2),
    status VARCHAR(50) NOT NULL,
    sender VARCHAR(255) NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT NOW()
);