name: Deploy Node.js App

on:
  push:
    branches:
      - dev
      - feature/id

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Deploy to Azure Dev App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'team3'
          publish-profile: ${{ secrets.AZURE_DEV_PUBLISH_PROFILE }}
          package: .
