name: Migrate Azure db with Flyway

on: workflow_dispatch {}

jobs:
  migrate-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup flyway CLI
        uses: red-gate/setup-flyway@v1

      - name: Run flyway migration
        env:
          PGHOST: ${{ secrets.PGHOST }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
        run: |
          flyway -url="jdbc:postgresql://$PGHOST/$PGDATABASE" -user="$PGUSER" -password="$PGPASSWORD" -locations="filesystem:db/migrations" migrate
